<?php $this->headLink()->appendStylesheet('/css/general.css'); ?>
<?php $this->headTitle( ": Account Created" ); ?>

<div id="view-content">
   <h2 id='title'>Account Created</h2>
   <div id='page-content'>

      <p>
      A new account has been created for you. However, before you can log in and
      start using this account, you must first validate you e-mail address. This
      is performed to ensure that you sign up with a working e-mail address, which
      you have access to.
      </p>
      <p>
      An e-mail has been sent to you with a validation code which you will need to
      uses to activate your account.
      </p>
      <p>
      <b><i>Please note:</i></b> that if you do not see the message in your inbox,
      the message may have incorrectly been identified as spam and that you will
      need to check your spam folder.
      </p>
   </div>
</div>
