<?php $this->headTitle(': Lost Account'); ?>
<?php $this->headLink()->appendStylesheet('/css/general.css') ?>

<div id="view-content">
   <h2 id='title'>Recover A Lost Account</h2>
   <div id='page-content'>
      <p class='msgs'>
      <?php if( isset( $this->msgs ) ) foreach( $this->msgs as $msg ) echo $msg; ?>
      </p>
      <p>
      Please enter your e-mail address and a new password will be sent to your account.
      </p>
      <?php echo $this->form->setAction($this->url()); ?>
      <p>
   </div>
</div>

