<?php $this->headTitle(': Change Password'); ?>
<?php $this->headLink()->appendStylesheet('/css/general.css') ?>

<?php $leaveStuddy_href =  $this->url( array('controller'=>'Revocation-of-Consent', 'action' => 'index' ),'default', true ) ?>


<div id="view-content">
   <h2 id='title'>Change you password</h2>
   <div id='page-content'>
      <p class='msgs'>
      <?php if( isset( $this->msgs ) ) foreach( $this->msgs as $msg ) echo $msg; ?>
      </p>
      <?php echo $this->form->setAction($this->url()); ?>
   </div>
   <h2 id='title'>Leave the study</h2>
   <div id='page-content'>
   <p>
   If you would like to leave the study please use the link below and follow the prompts. 
   Please not that once you have left the study you will nolonger be able to log in. 
   </p>
   <p>
   <a href='<?php echo $leaveStuddy_href; ?>' >I would like to leave this study</a>
   </p>
   </div>
</div>


