<?php $this->headTitle(': Login'); ?>
<?php $this->headLink()->appendStylesheet('/css/general.css') ?>

<?php $newuser_href =  $this->url( array('controller'=>'auth', 'action' => 'create-account' ),'default', true ) ?>


<div id="view-content">
   <h2 id='title'>Validate Account</h2>
   <div id='page-content'>
      <p class='msgs'>
      <?php if( isset( $this->msgs ) ) foreach( $this->msgs as $msg ) echo $msg; ?>
      </p>
      <p>
      Please enter your e-mail address along with the validation code sent to you.
      </p>
      <?php echo $this->form->setAction($this->url()); ?>
      <p>
      <b><i>Please note:</i></b> that if you did not find a validation message in 
      your inbox, it is possible that the message may have incorrectly been identified
      as spam.
      </p>
      <p>
      New user? create an account <a href="<?php echo $newuser_href; ?>">here</a>.
      </p>
   </div>
</div>


