<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php $this->headTitle(': Error'); ?>
  <?php $this->headLink()->appendStylesheet('/css/general.css') ?>
</head>


<body>
   <div id="view-content">

      <h2 id='title'>An error has occurred</h2>
      <div id='page-content'>
         <h2><?php echo $this->message ?></h2>

         <?php if (isset($this->exception)): ?>
  
            <h3>Exception information:</h3>
            <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  
            <h3>Stack trace:</h3>
            <pre><?php echo $this->exception->getTraceAsString() ?>
            </pre>

            <h3>Request Parameters:</h3>
            <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
            </pre>

         <?php endif ?>
      </div>
   </div>
</body>
</html>
