<?php $this->headTitle(': Request Denied'); ?>
<?php $this->headLink()->appendStylesheet('/css/general.css') ?>

<?php $this->headLink()->appendStylesheet( '/javascript/fancybox/jquery.fancybox-1.3.4.css' ); ?>
<?php $this->headScript()->appendFile( '/javascript/jquery-1.4.3.min.js' ); ?>
<?php $this->headScript()->appendFile( '/javascript/fancybox/jquery.easing-1.4.pack.js' ); ?>
<?php $this->headScript()->appendFile( '/javascript/fancybox/jquery.fancybox-1.3.4.pack.js' ); ?>

<div id="view-content">

<?php

   $id       = "inline";
   $class    = ""; //"test";
   $url      = "";//$this->url();
   $opentext = "open";
   $content  = "test test test test test test test test test test tes";
   $option = array(
                   'transitionIn'       => 'fade',
                   'transitionOut'      => 'fade',
                   'speedIn'            => 300,
                   'speedOut'           => 200,
                   'hideOnOverlayClick' => true,
                   'hideOnContentClick' => false,
                   'overlayShow'        => true,
                   'overlayColor'       => '#888',
                   'titleShow'          => true,
                   'titlePosition'      => 'over',
                   'showCloseButton'    => false,
                   );
  
 
   $fb = new Extend_Helpers_Fancybox( $option );
 
   echo $fb->createLink( array( 'id'=>1231, 'class' => 'test' ), $url, $opentext );
   echo $fb->createContent( 1231, $content );

   echo $fb->createLink( array( 'id'=>1233, 'class' => 'test' ), $url, $opentext );
   echo $fb->createContent( 1233, $content . "123331" );

   $this->headScript()->appendScript( $fb->getJavaScript() );
   
?>

</div>
