<body>
   <h4>To the Participant,</h4>
   
   <p>
   a recent change to your dispute incicates that you may be in a possition
   to resolve the dispute.
   </p>
   <p>   
   Please take the time to revisit your dispute and examine the changes made. 
   The following link will take you to the  
   <a href='<?php echo $this->href_base . $this->href_params; ?>' >ReConsider web site</a>.
   
   </p>
   </p>
   <p>   
   Thank you for your participation in this study.
   </p>
   <br />
   <br /> 
   ReConsider Team

</body>
