<body>
   <h4>To the Participant,</h4>
   
   <p>
   this email it to notify you that recently changes have been 
   made to your dispute by the other party. 
   </p>
   <p>
   Please take the time to revisit your dispute and examine the changes made.
   The following link will take you to the
   <a href='<?php echo $this->href_base . $this->href_params; ?>' >ReConsider web site</a>.

   </p>
   </p>
   <p>
   Thank you for your participation in this study.
   </p>
   <br />
   <br /> 
   ReConsider Team

</body>
