<?php $this->headTitle(': Outcome of Dispute'); ?>
<?php $this->headLink()->appendStylesheet('/css/general.css') ?>


<?php $back_href =  $this->url( array( 'controller'=> 'Disputes',
                                       'action'    => 'index' ),
                                       'default',
                                        true ) ?>

<div id="view-content">
   <h2 id='title'>Outcome of dispute</h2>
   <div id='page-content'>
      <p>
      TODO: this will display info about the agreements resulting from a concluded dispute.
      </p>
      <a href='<?php echo $back_href; ?>'>back</a>
   </div>
</div>

~             
