<?php $this->headLink()->appendStylesheet('/css/general.css') ?>
<?php $this->headTitle( ': Help' ); ?>

<div id="view-content">
   <h2 id='title'>Help Topics</h2>
   <div id='page-content'>
      <dl>
      <?php foreach( $this->index as $title=>$action ): ?>
      <?php $url = $this->url(  array( 'controller'=> 'Help',
                                       'action'    => $action )
                                       ); ?>
      <dt><a href='<?php echo $url; ?>' ><?php echo $title; ?></a></td>
      
      <?php endforeach; ?>
      </dl>
   </div>
</div>
