<?php $this->headLink()->appendStylesheet('/css/general.css') ?>
<?php $this->headTitle( ': System Requirements' ); ?>

<div id="view-content">
   <h2 id='title'>Help: System Requirements</h2>
   <div id='page-content' >
      <dl class='list'>
      <dt>Operating System:</dt>
         <dd>Windows XP, Vista, 7</dd>
         <dd>MAC OS 9 and later</dd>
         <dd>Linux</dd>
         <dd>Basicaly anything that can run one of the supported browsers.</dd>

      <dt>Browsers:</dt>
         <dd>Recomended: it is recomended that you use a Fire Fox browser</dd>
         <dd>Supported:  IE v6, Fire Fox v3.6+ and Chrom 16.0.912.63 beta </dd>
         <dd>Partialy supported: version of EI which come with windows vist and 7</dd>
         <dd>Other browsers such as Safari, Konqueror and Opera should work, however, are currently unconfirmed.</dd>

      <dt>Other:</dt>
         <dd>JavaScript</dd>
         <dd>Flash – not strictly necessary, but, recommended.</dd>
      </dl>

      <h3 class='sub-title'>I need to update or get one of the thing listed about, where should I look?</h3>
      <dl class='list' >
      <dt>Browsers:</dt>
         <dd>Download IE from <a href='http://windows.microsoft.com/en-AU/internet-explorer/products/ie/home'
                                 >http://windows.microsoft.com/en-AU/internet-explorer/products/ie/home</a></dd>
         <dd>Download Firefox from <a href='http://www.mozilla.org/en-US/firefox/new/'
                                     >http://www.mozilla.org/en-US/firefox/new/</a></dd>

      <dt>JavaScript</dt>
         <dd>Please refer to your browser's support manual.</dd>

      <dt>Flash</dt>
         <dd><a href='http://get.adobe.com/flashplayer/otherversions/'
                >http://get.adobe.com/flashplayer/otherversions/</a></dd>
      </dl>
   </div>
</div>
