<body>

<h4>To the Participant,</h4>
<p>
you are receving this email because a request was made to recover 
you account on the ReConsider online dispute resolution system.
Below is a new password which you can use to log in to the site.
</p>
<p>
Your new password is: <?php echo $this->passwd; ?>
</p>
<p>
You can log in to your account here: <a href='<?php echo $this->href_base;  ?>'><?php echo $this->href_base;  ?></a>
</p>
<p>
Please note that you can still log in with your old password and
if you did not request a new password, this process will not 
interfere, with your account.
</p>
<p>
<br />
The ReConsider Team.
</p>
</body>
