<body>
   <h4>To the Participant,</h4>

   <p> 
   this email has been sent to you because you requested a new email
   validation code.
   </p>   
   <p>   
   Please use the link provided. This link will take you to     
   a page were you will need to enter your email address and     
   the activation key provided bellow. If you use the link the this field  
   should automaticaly be filled for you.        
   
   </p>
   <p>   
   Activation key: <b><?php echo $this->validationCode; ?></b>          
   
   </p>
   <p>   
   Activation Link <a href = '<?php echo $this->href_base . $this->href_params; ?>' ><?php echo $this->href_base . $this->href_params; ?></a>         
   
   </p>
   <p>   
   If you did not sign your self up and/or would not like to participate   
   in this study, please disreagred this message.             
   
   </p>
   <p>   
   In either event, you email will be keep on file until the compleation   
   of the study. At no point will you email address be provided to a third 
   party. However, if you do proceed, your email address will be used to   
   notify you of changes to your dispute.        
   
   </p>
   <br />
   <br /> 
   ReConsider Team

</body>
